# Generated by Django 5.2.17 on 2026-09-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Дата рождения', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='message_privacy',
            field=models.CharField(choices=[('everyone', 'Все'), ('contacts', 'Контакты'), ('nobody', 'Никто')], default='everyone', help_text='Кто может отправлять мне сообщения', max_length=20),
        ),
    ]
