# Generated by Django 5.2.17 on 2026-10-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privacy_accepted_at',
            field=models.DateTimeField(blank=True, help_text='Когда дано согласие на обработку персональных данных', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_version',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text='Когда приняты правила использование равел', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_version',
            field=models.CharField(blank=True, default='', help_text='Версия правил, принятые при регистрации', max_length=16),
        ),
    ]
