# Generated by Django 5.2.17 on 2026-09-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_type',
            field=models.CharField(choices=[('none', 'Нет'), ('image', 'Изображение'), ('audio', 'Аудио'), ('video', 'Видео'), ('file', 'Файл')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_url',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='message',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Длительность аудио/видео в секундах', null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
