# Generated by Django 5.2.17 on 2026-09-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_readstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='transcription',
            field=models.TextField(blank=True, default='', help_text='Транскрипция голосового сообщения'),
        ),
    ]
