# Generated by Django 5.2.17 on 2026-09-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message_transcription'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('group', 'Группа'), ('channel', 'Канал'), ('direct', 'Личный чат')], default='group', max_length=10),
        ),
    ]
