# Generated by Django 5.2.17 on 2026-09-13 11:01

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_move_rooms_to_default_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='invite_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Токен для ссылки-приглашения на сервер', unique=True),
        ),
    ]
